Add workerType
moj-analytical-services/etl_manager pull request #152
Opened 2024-06-19 10:18 UTC by samnlindsay

https://docs.aws.amazon.com/glue/latest/webapi/API_CreateJob.html#Glue-CreateJob-request-WorkerType

Enabling different worker types to make more cost-effective use of resources (i.e. doubling DPUs per worker rather than doubling the number of workers).

https://aws.amazon.com/blogs/big-data/scale-your-aws-glue-for-apache-spark-jobs-with-new-larger-worker-types-g-4x-and-g-8x/

2024-06-19 12:16 UTC, RobinL approved these changes

2024-06-19 12:18 UTC, RobinL reviewed
Nice. Prob want to bump version in case this breaks any historic code

2024-06-19 12:46 UTC, Thomas-Hirsch commented
[semver](https://semver.org/) would suggest changing the major version gvien it's a breaking change. As mentioned on slack, [it is possible to do this without needing to make this change](https://github.com/moj-analytical-services/airflow-family-ap/blob/master/python_scripts/run_derived_table.py), though I admit this is a bit of a workaround.

2024-06-21 14:36 UTC, Thomas-Hirsch requested changes
The changes are fine, but as mentioned you should bump the version to v8.0.0 to reflect the breaking changes

2024-06-24 09:20 UTC, Thomas-Hirsch reviewed
could I trouble you to update the changelog too?

2024-06-24 09:51 UTC, samnlindsay commented
> could I trouble you to update the changelog too?

I knew that was coming 😂

2024-06-25 10:11 UTC, Thomas-Hirsch approved these changes

2024-06-25 10:13 UTC, merged